config/routes.rb
Rails.application.routes.draw do
  
  root "votaciones#listar"
  post "votaciones/:id_restaurante/puntaje/:id_puntaje", to: "votaciones#votar", as: 'votar_restaurante'


  # Rutas Tipos Comidas
  get      'tipos_comidas',             to: 'tipos_comidas#listar',     as: 'tipos_comidas'     # listar 
  get      'tipos_comidas/nuevo',       to: 'tipos_comidas#crear',      as: 'nuevo_tipo_comida' # formulario de nuevo
  get      'tipos_comidas/:id',         to: 'tipos_comidas#mostrar',    as: 'tipo_comida'       # vista del detalle de un tipo de comida
  get      'tipos_comidas/:id/editar',  to: 'tipos_comidas#editar',     as: 'editar_tipo_comida'# formulario para editar el registro

  post     'tipos_comidas',             to: 'tipos_comidas#guardar'
  put      'tipos_comidas/:id',         to: 'tipos_comidas#actualizar'
  patch    'tipos_comidas/:id',         to: 'tipos_comidas#actualizar'
  delete   'tipos_comidas/:id',         to: 'tipos_comidas#eliminar'

  # Rutas Puntajes
  get       'puntajes',                 to: 'puntajes#listar',          as: 'puntajes'
  get       'puntajes/nuevo',           to: 'puntajes#crear',           as: 'nuevo_puntaje'
  get       'puntajes/:id',             to: 'puntajes#mostrar',         as: 'puntaje'
  get       'puntajes/:id/editar',      to: 'puntajes#editar',          as: 'editar_puntaje'

  post      'puntajes',                 to: 'puntajes#guardar'
  put       'puntajes/:id',             to: 'puntajes#actualizar'
  patch     'puntajes/:id',             to: 'puntajes#actualizar'
  delete    'puntajes/:id',             to: 'puntajes#eliminar'

  # Usuarios
  get       'usuarios',                 to: 'usuarios#listar',        as: 'usuarios'
  get       'usuarios/nuevo',           to: 'usuarios#crear',         as: 'nuevo_usuario'
  get       'usuarios/:id',             to: 'usuarios#mostrar',       as: 'usuario'
  get       'usuarios/:id/editar',      to: 'usuarios#editar',        as: 'editar_usuario'

  post      'usuarios',                 to: 'usuarios#guardar'       
  patch     'usuarios/:id',             to: 'usuarios#actualizar'
  put       'usuarios/:id',             to: 'usuarios#actualizar' # buena práctica colocar el PUT 
  delete    'usuarios/:id',             to: 'usuarios#eliminar'

  # Restaurantes
  get           'restaurantes',               to: 'restaurantes#listar',  as: 'restaurantes'
  get           'restaurantes/nuevo',         to: 'restaurantes#crear',   as: 'nuevo_restaurante'
  get           'restaurantes/:id',           to: 'restaurantes#mostrar', as: 'restaurante'
  get           'restaurantes/:id/editar',    to: 'restaurantes#editar',  as: 'editar_restaurante'

  post          'restaurantes',               to: 'restaurantes#guardar'
  patch         'restaurantes/:id',           to: 'restaurantes#actualizar'
  # put           'restaurantes/:id',           to: 'restaurantes#actualizar'
  delete        'restaurantes/:id',           to: 'restaurantes#eliminar'

  # Platos

  get 'platos',             to: 'platos#listar', as: 'platos'
  get 'platos/crear',       to: 'platos#crear', as: 'nuevo_plato'
  get 'platos/:id',         to: 'platos#mostrar', as: 'plato'
  get 'platos/:id/editar',  to: 'platos#editar', as: 'editar_plato'

  post    'platos',            to: 'platos#guardar'
  patch   'platos',            to: 'platos#actualizar'
  put     'platos',            to: 'platos#actualizar'
  delete  'platos',            to: 'platos#eliminar'
end

app/controllers/tipos_comidas_controller.rb
# Los controladores son en "plural" y hacen referencia al modelo 
class TiposComidasController < ApplicationController

    before_action :asignar_tipo_comida, only: [:mostrar, :editar, :actualizar, :eliminar]

    # before_action :mostrar_mensaje_antes, only: [:listar]
    # after_action  :mostrar_mensaje_despues

    # GET /tipos_comidas
    def listar
        @todos_los_tipos = TipoComida.all.order(id: :asc)
        @titulo_link = "Registrar nuevo tipo de comida"
    end

    # GET /tipos_comidas/nuevo
    def crear
        @tipo_comida = TipoComida.new
    end

    # GET /tipos_comidas/:id
    def mostrar
        # vista para mostrar el detalle de un tipo de comida
        # por ejemplo, podríamos mostrar todos los restaruantes adjuntos
    end

    # GET /tipos_comidas/:id/editar
    def editar
        # mostrar el formulario con los datos de un registro para cambiarlos
    end

    # POST /tipos_comidas
    def guardar
        # guardar lo que llegue del formulario en la base de datos
        datos_tipo_comida = params.require(:tipo_comida).permit(:tipo) # REPETIDO 💔
        @tipo_comida = TipoComida.new(datos_tipo_comida)
        if @tipo_comida.save # pregunta por las valiciones, SI pasa todas, se guarda, SINO, agregar un hash de errores
            redirect_to tipos_comidas_path
        else
            render :crear # prestado una vista
        end        
    end

    def actualizar
        # encontrar el registro que quiero editar en la BD
        datos_tipo_comida = params.require(:tipo_comida).permit(:tipo) # REPETIDO 💔
        # actualizar los campos necesarios
        @tipo_comida.tipo = datos_tipo_comida[:tipo]
        # guardar los cambios en la base de datos
        @tipo_comida.save
        # redireccionar a la lista de todos los tipos de comida
        redirect_to tipos_comidas_path
    end

    # DELETE /tipos_comidas/:id
    def eliminar
        # pasos para eliminar un registro
        # 1. buscar el registro por ID
        # 2. Intentar eliminar el registro
        @tipo_comida.destroy
        redirect_to tipos_comidas_path
    end

    private # todos los métodos de aquí hacia abajo SON PRIVADOS 🔐

    def asignar_tipo_comida
        @tipo_comida = TipoComida.find(params[:id])
    end
    
    def mostrar_mensaje_antes
        puts "HOLA ANTES DEL ACTION 🚚"
    end

    def mostrar_mensaje_despues
        puts "HOLA DESPUÉS DEL ACTION 🖖"
    end
end

app/views/tipos_comidas/_formulario.html.erb
<%= form_with(model: base_tipo_comida) do |formulario| %>
    <%= formulario.label        :tipo %>
    <%= formulario.text_field   :tipo %>
    <% if base_tipo_comida.errors[:tipo].any? %>
        <div class="alert alert-warning" role="alert">
            <%= base_tipo_comida.errors[:tipo].first %>
        </div>
    <% end %>
    <%= formulario.submit %>
<% end %>

app/views/tipos_comidas/crear.html.erb
<h1>Formulario para crear un nuevo tipo de comida</h1>

<%= render 'formulario', base_tipo_comida: @tipo_comida  %>
<%= link_to 'Volver', tipos_comidas_path %>

app/views/tipos_comidas/editar.html.erb
<h2>Editar el tipo de comida</h2>

<%= render 'formulario', base_tipo_comida: @tipo_comida %>
<%= link_to tipos_comidas_path do%>
    Volver
<% end %>

app/views/tipos_comidas/listar.html.erb
<h1>
    Listar los tipos de restaurantes
</h1>

<%= link_to @titulo_link, nuevo_tipo_comida_path, class: 'btn btn-primary' %>

<table class="table">
    <tr>
        <th>id</th>
        <th class="text-center">tipo</th>
        <th class="text-end">acciones</th>
    </tr>
    <% @todos_los_tipos.each do |tipo_comida| %>
        <tr>
            <td> <%= tipo_comida.id %> </td>
            <td class="text-center"> 
                <%= link_to tipo_comida_path(tipo_comida) do %>
                    <%= tipo_comida.tipo %>
                <% end %>
            </td>
            <td class="text-end">
                <%= link_to tipo_comida_path(tipo_comida), class: 'btn btn-danger', method: :delete, data: { confirm: '¿Está seguro que quiere eliminar el registro?' } do %>
                    <i class="fas fa-eraser"></i>
                    Borrar
                <% end %>
                <%= link_to editar_tipo_comida_path(tipo_comida), class: 'btn btn-warning' do %>
                    <i class="fas fa-edit"></i>
                    Editar
                <% end %>
            </td>
        </tr>
    <% end %>
</table>

app/views/tipos_comidas/mostrar.html.erb
<h2>Detalles del Tipo de Comida</h2>

<h3>id: <%= @tipo_comida.id %> </h3>
<h1> <%= @tipo_comida.tipo %> </h1>

<% @tipo_comida.restaurantes.each do |restaurante| %>
    <p> <%= restaurante.nombre %> </p>
<% end %>
<%= link_to tipos_comidas_path do %>
    Volver
<% end %>