config/routes.rb
Rails.application.routes.draw do
  
  root "votaciones#listar"
  post "votaciones/:id_restaurante/puntaje/:id_puntaje", to: "votaciones#votar", as: 'votar_restaurante'


  # Rutas Tipos Comidas
  get      'tipos_comidas',             to: 'tipos_comidas#listar',     as: 'tipos_comidas'     # listar 
  get      'tipos_comidas/nuevo',       to: 'tipos_comidas#crear',      as: 'nuevo_tipo_comida' # formulario de nuevo
  get      'tipos_comidas/:id',         to: 'tipos_comidas#mostrar',    as: 'tipo_comida'       # vista del detalle de un tipo de comida
  get      'tipos_comidas/:id/editar',  to: 'tipos_comidas#editar',     as: 'editar_tipo_comida'# formulario para editar el registro

  post     'tipos_comidas',             to: 'tipos_comidas#guardar'
  put      'tipos_comidas/:id',         to: 'tipos_comidas#actualizar'
  patch    'tipos_comidas/:id',         to: 'tipos_comidas#actualizar'
  delete   'tipos_comidas/:id',         to: 'tipos_comidas#eliminar'

  # Rutas Puntajes
  get       'puntajes',                 to: 'puntajes#listar',          as: 'puntajes'
  get       'puntajes/nuevo',           to: 'puntajes#crear',           as: 'nuevo_puntaje'
  get       'puntajes/:id',             to: 'puntajes#mostrar',         as: 'puntaje'
  get       'puntajes/:id/editar',      to: 'puntajes#editar',          as: 'editar_puntaje'

  post      'puntajes',                 to: 'puntajes#guardar'
  put       'puntajes/:id',             to: 'puntajes#actualizar'
  patch     'puntajes/:id',             to: 'puntajes#actualizar'
  delete    'puntajes/:id',             to: 'puntajes#eliminar'

  # Usuarios
  get       'usuarios',                 to: 'usuarios#listar',        as: 'usuarios'
  get       'usuarios/nuevo',           to: 'usuarios#crear',         as: 'nuevo_usuario'
  get       'usuarios/:id',             to: 'usuarios#mostrar',       as: 'usuario'
  get       'usuarios/:id/editar',      to: 'usuarios#editar',        as: 'editar_usuario'

  post      'usuarios',                 to: 'usuarios#guardar'       
  patch     'usuarios/:id',             to: 'usuarios#actualizar'
  put       'usuarios/:id',             to: 'usuarios#actualizar' # buena práctica colocar el PUT 
  delete    'usuarios/:id',             to: 'usuarios#eliminar'

  # Restaurantes
  get           'restaurantes',               to: 'restaurantes#listar',  as: 'restaurantes'
  get           'restaurantes/nuevo',         to: 'restaurantes#crear',   as: 'nuevo_restaurante'
  get           'restaurantes/:id',           to: 'restaurantes#mostrar', as: 'restaurante'
  get           'restaurantes/:id/editar',    to: 'restaurantes#editar',  as: 'editar_restaurante'

  post          'restaurantes',               to: 'restaurantes#guardar'
  patch         'restaurantes/:id',           to: 'restaurantes#actualizar'
  # put           'restaurantes/:id',           to: 'restaurantes#actualizar'
  delete        'restaurantes/:id',           to: 'restaurantes#eliminar'

  # Platos

  get 'platos',             to: 'platos#listar', as: 'platos'
  get 'platos/crear',       to: 'platos#crear', as: 'nuevo_plato'
  get 'platos/:id',         to: 'platos#mostrar', as: 'plato'
  get 'platos/:id/editar',  to: 'platos#editar', as: 'editar_plato'

  post    'platos',            to: 'platos#guardar'
  patch   'platos',            to: 'platos#actualizar'
  put     'platos',            to: 'platos#actualizar'
  delete  'platos',            to: 'platos#eliminar'
end

app/models/plato.rb
class Plato < ApplicationRecord
    belongs_to :restaurante

    has_many :puntajes_platos
    has_many :puntajes, through: :puntajes_platos

    validates(:nombre, presence: true)
    validates(:descripcion, presence: true)
    validates(:restaurante_id, presence: true)
end

app/controllers/platos_controller.rb
class PlatosController < ApplicationController

    before_action :asignar_plato, only: [:mostrar, :editar, :actualizar, :eliminar]
    before_action :consultar_restaurantes, only: [:crear, :editar]
  
    def listar
      @platos = Plato.all
    end
  
    def crear
      @plato = Plato.new
    end
  
    def mostrar
    end
  
    def editar
  
    end
  
    def guardar
      @plato = Plato.new(params_plato)
      if @plato.save
        redirect_to plato_path(@plato)
      else
        consultar_restaurantes
        render :crear
      end
    end
  
    def actualizar
      if @plato.update(params_plato)
        redirect_to plato_path(@plato)
      else
        consultar_restaurantes
        render :editar
      end
    end
  
    def eliminar
      @plato.destroy
    end
  
    private
    def asignar_plato
      @plato = Plato.find(params[:id])
    end
  
    def params_plato
      params.require(:plato).permit(:nombre, :descripcion, :restaurante_id)
    end
  
    def consultar_restaurantes
      @restaurantes = Restaurante.all
    end
  end

app/helpers/platos_helper.rb
module PlatosHelper
end

app/views/platos/_formulario.html.erb
<%= form_with(model: base_plato) do |formulario| %>
    <div class="mb-3">
        <%= formulario.label :nombre, class: 'form-label' %>
        <%= formulario.text_field :nombre, class: 'form-control' %>
        <% if base_plato.errors[:nombre].any? %>
            <div>
                <%= base_plato.errors[:nombre].first %>
            </div>
        <% end %>
    </div>
    <div class="mb-3">
        <%= formulario.label :descripcion, class: 'form-label' %>
        <%= formulario.text_field :descripcion, class: 'form-control' %>
        <% if base_plato.errors[:descripcion].any? %>
            <div>
                <%= base_plato.errors[:descripcion].first %>
            </div>
        <% end %>
    </div>
    <div class="mb-3">
        <%= formulario.label :restaurante_id, class: 'form-label' %>
        <%= formulario.select :restaurante_id, 
            options_from_collection_for_select(restaurantes, :id, :nombre, base_plato.restaurante_id),
            { include_blank: 'Elige un restaurante' },
            class: "form-select" %>
        <% if base_plato.errors[:restaurante_id].any? %>
            <div>
                <%= base_plato.errors[:restaurante_id].first %>
            </div>
        <% end %>
    </div>

    <%= formulario.submit %>
<% end %>

app/views/platos/crear.html.erb
<h1>Crear Plato</h1>

<%= render "formulario", base_plato: @plato, restaurantes: @restaurantes %>
<%= link_to "Volver", platos_path %>

app/views/platos/editar.html.erb
<h1>Editar Plato</h1>

<%= render "formulario", base_plato: @plato, restaurantes: @restaurantes %>

<%= link_to "Volver", platos_path %>

app/views/platos/listar.html.erb
<h1>Platos</h1>

<%= link_to "Crear plato", nuevo_plato_path %>

<table class="table">
    <tr>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Restaurante</th>
        <th>Acciones</th>
    </tr>
    <% @platos.each do |plato| %>
        <tr>
            <td><%= plato.nombre %></td>
            <td><%= plato.descripcion %></td>
            <td><%= plato.restaurante.nombre %></td>
            <td>
                <%= link_to "Editar", editar_plato_path(plato) %>
                <%= link_to "Eliminar", plato_path(plato), method: :delete, data: { confirm: "¿Seguro que quiere eliminar el plato?" } %>
            </td>
        </tr>
    <% end %>
</table>

app/views/platos/mostrar.html.erb
<h1>Platos#mostrar</h1>
<p>Find me in app/views/platos/mostrar.html.erb</p>