config/routes.rb
Rails.application.routes.draw do
  
  root "votaciones#listar"
  post "votaciones/:id_restaurante/puntaje/:id_puntaje", to: "votaciones#votar", as: 'votar_restaurante'


  # Rutas Tipos Comidas
  get      'tipos_comidas',             to: 'tipos_comidas#listar',     as: 'tipos_comidas'     # listar 
  get      'tipos_comidas/nuevo',       to: 'tipos_comidas#crear',      as: 'nuevo_tipo_comida' # formulario de nuevo
  get      'tipos_comidas/:id',         to: 'tipos_comidas#mostrar',    as: 'tipo_comida'       # vista del detalle de un tipo de comida
  get      'tipos_comidas/:id/editar',  to: 'tipos_comidas#editar',     as: 'editar_tipo_comida'# formulario para editar el registro

  post     'tipos_comidas',             to: 'tipos_comidas#guardar'
  put      'tipos_comidas/:id',         to: 'tipos_comidas#actualizar'
  patch    'tipos_comidas/:id',         to: 'tipos_comidas#actualizar'
  delete   'tipos_comidas/:id',         to: 'tipos_comidas#eliminar'

  # Rutas Puntajes
  get       'puntajes',                 to: 'puntajes#listar',          as: 'puntajes'
  get       'puntajes/nuevo',           to: 'puntajes#crear',           as: 'nuevo_puntaje'
  get       'puntajes/:id',             to: 'puntajes#mostrar',         as: 'puntaje'
  get       'puntajes/:id/editar',      to: 'puntajes#editar',          as: 'editar_puntaje'

  post      'puntajes',                 to: 'puntajes#guardar'
  put       'puntajes/:id',             to: 'puntajes#actualizar'
  patch     'puntajes/:id',             to: 'puntajes#actualizar'
  delete    'puntajes/:id',             to: 'puntajes#eliminar'

  # Usuarios
  get       'usuarios',                 to: 'usuarios#listar',        as: 'usuarios'
  get       'usuarios/nuevo',           to: 'usuarios#crear',         as: 'nuevo_usuario'
  get       'usuarios/:id',             to: 'usuarios#mostrar',       as: 'usuario'
  get       'usuarios/:id/editar',      to: 'usuarios#editar',        as: 'editar_usuario'

  post      'usuarios',                 to: 'usuarios#guardar'       
  patch     'usuarios/:id',             to: 'usuarios#actualizar'
  put       'usuarios/:id',             to: 'usuarios#actualizar' # buena práctica colocar el PUT 
  delete    'usuarios/:id',             to: 'usuarios#eliminar'

  # Restaurantes
  get           'restaurantes',               to: 'restaurantes#listar',  as: 'restaurantes'
  get           'restaurantes/nuevo',         to: 'restaurantes#crear',   as: 'nuevo_restaurante'
  get           'restaurantes/:id',           to: 'restaurantes#mostrar', as: 'restaurante'
  get           'restaurantes/:id/editar',    to: 'restaurantes#editar',  as: 'editar_restaurante'

  post          'restaurantes',               to: 'restaurantes#guardar'
  patch         'restaurantes/:id',           to: 'restaurantes#actualizar'
  # put           'restaurantes/:id',           to: 'restaurantes#actualizar'
  delete        'restaurantes/:id',           to: 'restaurantes#eliminar'

  # Platos

  get 'platos',             to: 'platos#listar', as: 'platos'
  get 'platos/crear',       to: 'platos#crear', as: 'nuevo_plato'
  get 'platos/:id',         to: 'platos#mostrar', as: 'plato'
  get 'platos/:id/editar',  to: 'platos#editar', as: 'editar_plato'

  post    'platos',            to: 'platos#guardar'
  patch   'platos',            to: 'platos#actualizar'
  put     'platos',            to: 'platos#actualizar'
  delete  'platos',            to: 'platos#eliminar'
end

app/models/puntaje.rb
# Modelo va en singular
class Puntaje < ApplicationRecord

    before_validation :capitalizar

    has_many :puntajes_platos
    has_many :puntajes_restaurantes

    
    validates(:tipo, presence: true)
    validates(:tipo, uniqueness: true)

    private
    def capitalizar
        self.tipo.capitalize!
    end
end

app/controllers/puntajes_controller.rb
class PuntajesController < ApplicationController

  before_action :asignar_puntaje, only: [:mostrar, :editar, :actualizar, :eliminar]
  # GET /puntajes
  def listar
      @todos_los_puntajes = Puntaje.all
  end

  # GET /puntajes/nuevo
  def crear
      @puntaje = Puntaje.new
  end

  # GET /puntajes/:id
  def mostrar

  end

  # GET /puntajes/:id/editar
  def editar

  end

  # POST /puntajes
  def guardar
      @puntaje = Puntaje.new(params_puntaje)
      if @puntaje.save        
          redirect_to puntajes_path
      else
          render :crear
      end
  end

  # PUT   /puntajes/:id
  # PATCH /puntajes/:id
  def actualizar
      
      @puntaje.tipo = params_puntaje[:tipo]
      @puntaje.save
      redirect_to puntajes_path
  end

  # DELETE /puntajes/:id    
  def eliminar
      @puntaje.destroy
      redirect_to puntajes_path
  end

  private
  def asignar_puntaje
      @puntaje = Puntaje.find(params[:id])
  end

  def params_puntaje
      params.require(:puntaje).permit(:tipo)
  end
end

app/views/puntajes/_formulario.html.erb
<div class="mb-3">
<%= form_with(model: base_puntaje) do |formulario| %>
    <%= formulario.label        :tipo, class:"form-label" %>
    <%= formulario.text_field   :tipo, class:"form-control mb-3" %>
    <%= formulario.submit class:"btn btn-secondary" %>
<% end %>
</div>

app/views/puntajes/crear.html.erb
<h1>Formulario para crear un nuevo puntaje</h1>

<%= render 'formulario', base_puntaje: @puntaje %>

<%= link_to puntajes_path, class:"btn btn-primary" do%>
<i class="fas fa-arrow-circle-left" ></i>
volver
<%end%>

app/views/puntajes/editar.html.erb
<h1>Formulario para Editar Puntaje</h1>

<%= render 'formulario', base_puntaje: @puntaje %>

<%= link_to puntajes_path, class:"btn btn-primary" do%>
<i class="fas fa-arrow-circle-left" ></i>
volver
<%end%>

app/views/puntajes/listar.html.erb
<h1>Sistema de Puntaje para Restaurantes</h1>
<%= link_to nuevo_puntaje_path, class: "btn btn-primary" do %>Ir al formulario <i class="fas fa-arrow-circle-right"></i>
<%end%>
<table class="table">
    <tr>
        <th >ID</th>
        <th class="text-center">Tipo</th>
        <th class="text-end">Acciones</th>
    </tr>

    <% @todos_los_puntajes.each do |puntaje| %>
        <tr>
            <td style="width:50px"> <%= puntaje.id %> </td>
            <td class="text-center"> 
            <%= link_to puntaje_path(puntaje) do %>
             <%= puntaje.tipo %>
            <%end%>
            </td>
            <td class="text-end">
                <%= link_to puntaje_path(puntaje), class: "btn btn-danger", method: :delete, data: { confirm: 'Desea eliminar el registro'} do %>
                <i class="fas fa-trash "></i> Borrar
            <% end %>
            <%= link_to editar_puntaje_path(puntaje), class: "btn btn-warning" do %>
            <i class="far fa-edit"></i> Editar
            <%end%>
            </td>
        </tr>
    <% end %>

app/views/puntajes/mostrar.html.erb
<h2>Detalle Puntaje</h2>
<h3>id: <%= @puntaje.id %></h3>
<h1><%= @puntaje.tipo %></h1>



<%= link_to puntajes_path, class:"btn btn-primary" do %>
<i class="fas fa-arrow-circle-left"></i>Volver
<%end%>