config/routes.rb
Rails.application.routes.draw do
  
  root "votaciones#listar"
  post "votaciones/:id_restaurante/puntaje/:id_puntaje", to: "votaciones#votar", as: 'votar_restaurante'


  # Rutas Tipos Comidas
  get      'tipos_comidas',             to: 'tipos_comidas#listar',     as: 'tipos_comidas'     # listar 
  get      'tipos_comidas/nuevo',       to: 'tipos_comidas#crear',      as: 'nuevo_tipo_comida' # formulario de nuevo
  get      'tipos_comidas/:id',         to: 'tipos_comidas#mostrar',    as: 'tipo_comida'       # vista del detalle de un tipo de comida
  get      'tipos_comidas/:id/editar',  to: 'tipos_comidas#editar',     as: 'editar_tipo_comida'# formulario para editar el registro

  post     'tipos_comidas',             to: 'tipos_comidas#guardar'
  put      'tipos_comidas/:id',         to: 'tipos_comidas#actualizar'
  patch    'tipos_comidas/:id',         to: 'tipos_comidas#actualizar'
  delete   'tipos_comidas/:id',         to: 'tipos_comidas#eliminar'

  # Rutas Puntajes
  get       'puntajes',                 to: 'puntajes#listar',          as: 'puntajes'
  get       'puntajes/nuevo',           to: 'puntajes#crear',           as: 'nuevo_puntaje'
  get       'puntajes/:id',             to: 'puntajes#mostrar',         as: 'puntaje'
  get       'puntajes/:id/editar',      to: 'puntajes#editar',          as: 'editar_puntaje'

  post      'puntajes',                 to: 'puntajes#guardar'
  put       'puntajes/:id',             to: 'puntajes#actualizar'
  patch     'puntajes/:id',             to: 'puntajes#actualizar'
  delete    'puntajes/:id',             to: 'puntajes#eliminar'

  # Usuarios
  get       'usuarios',                 to: 'usuarios#listar',        as: 'usuarios'
  get       'usuarios/nuevo',           to: 'usuarios#crear',         as: 'nuevo_usuario'
  get       'usuarios/:id',             to: 'usuarios#mostrar',       as: 'usuario'
  get       'usuarios/:id/editar',      to: 'usuarios#editar',        as: 'editar_usuario'

  post      'usuarios',                 to: 'usuarios#guardar'       
  patch     'usuarios/:id',             to: 'usuarios#actualizar'
  put       'usuarios/:id',             to: 'usuarios#actualizar' # buena práctica colocar el PUT 
  delete    'usuarios/:id',             to: 'usuarios#eliminar'

  # Restaurantes
  get           'restaurantes',               to: 'restaurantes#listar',  as: 'restaurantes'
  get           'restaurantes/nuevo',         to: 'restaurantes#crear',   as: 'nuevo_restaurante'
  get           'restaurantes/:id',           to: 'restaurantes#mostrar', as: 'restaurante'
  get           'restaurantes/:id/editar',    to: 'restaurantes#editar',  as: 'editar_restaurante'

  post          'restaurantes',               to: 'restaurantes#guardar'
  patch         'restaurantes/:id',           to: 'restaurantes#actualizar'
  # put           'restaurantes/:id',           to: 'restaurantes#actualizar'
  delete        'restaurantes/:id',           to: 'restaurantes#eliminar'

  # Platos

  get 'platos',             to: 'platos#listar', as: 'platos'
  get 'platos/crear',       to: 'platos#crear', as: 'nuevo_plato'
  get 'platos/:id',         to: 'platos#mostrar', as: 'plato'
  get 'platos/:id/editar',  to: 'platos#editar', as: 'editar_plato'

  post    'platos',            to: 'platos#guardar'
  patch   'platos',            to: 'platos#actualizar'
  put     'platos',            to: 'platos#actualizar'
  delete  'platos',            to: 'platos#eliminar'
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
    <a class="navbar-brand" href="#">Votaciones Comidas 🗳</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to "Tipos Comidas", tipos_comidas_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
            <%= link_to "Restaurantes", restaurantes_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
            <%= link_to "Platos", platos_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
            <%= link_to "Usuarios", usuarios_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
            <%= link_to "Puntajes", puntajes_path, class: 'nav-link active' %>
        </li>
        </ul>
    </div>
    </div>
</nav>

app/views/layouts/_menu_vertical.html.erb
<div style="position: fixed; height: 100%; background-color: black; color: white;">
    <h2>Menu vertical</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurantes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
    <script src="https://kit.fontawesome.com/19ecb226ec.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render "layouts/menu" %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>